name: todo_shopping_list_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.2.0+2
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.0.0
  nested: any
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
